"""eps* when an auditor POOLS its sessions instead of flagging on any single one.

EXPLORATORY, NOT SEALED; added after the second skeptical review
(paper/REVIEW_skeptical_2.md, M1).

The sealed eps* rule lets an auditor run k independent sessions and raise an
alarm if ANY one of them crosses its single-session threshold, with k capped so
that 1 - (1 - f)^k stays within the 5% false-alarm budget. That never combines
evidence across sessions. Here the auditor instead fixes k in advance and runs
ONE test: a one-sided Welch t-test of its mean session score over the k suspect
sessions against the mean over the 300 sealed honest calibration sessions, at
the 5% budget.

A first version compared the k-session mean with a bootstrap quantile of the
calibration mean. Its false-alarm rate on the holdout grew with k (33% for OTE at
k = 128), because it ignored the uncertainty in the calibration mean itself,
which dominates once k approaches the calibration size. The two-sample test
accounts for it; its false-alarm rate is checked on the 500 holdout sessions,
which it never sees. It also means pooling cannot detect a shift smaller than
the honest calibration set can resolve: more suspect sessions alone do not help.

  * The false-alarm check must use FRESH draws: the 800 honest sessions
    (300 calibration + 500 holdout, exchangeable A0 sessions on distinct seeds)
    are repeatedly split at random into 300 calibration sessions and k suspect
    sessions drawn without replacement. (Resampling k sessions from one fixed
    holdout, as a second version did, measures the chance gap between two finite
    samples, not the test's error rate.)
  * Power at each eps: 300 calibration sessions drawn from the honest pool, k
    suspect sessions drawn without replacement from the 200 A3 sessions at that
    eps. So k is capped at 128; within that cap, k may be as large as the
    adversary's saving pays for. The 300 honest calibration sessions are not
    counted in the cost, as in the sealed analysis.

Scores are the auditors' own session scores (FUSE: log10 of its e-value).

    python scripts/19_pooled_sessions.py

Output: results/v2/tables/pooled_sessions.md
"""

from __future__ import annotations

import importlib.util
import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from arena.protocol import load_sealed  # noqa: E402

_spec = importlib.util.spec_from_file_location("paper15", ROOT / "scripts" / "15_paper.py")
P = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(P)

OUT = P.TAB / "pooled_sessions.md"
BUDGET = 0.05            # the sealed family false-alarm budget, now spent on one test
TARGET = 0.80            # the sealed power target
K_GRID = [2, 4, 8, 16, 32, 64, 128]
M_CAL = 300
REPS = 2000
SEED = 0


def scores(rows, name):
    return np.array([s for r in rows if (s := P.score_of(r["auditors"][name], name)) is not None], float)


def welch_reject(x, c) -> bool:
    """One-sided Welch t-test: is mean(x) above mean(c) at the 5% budget?"""
    from scipy.stats import ttest_ind
    return bool(ttest_ind(x, c, equal_var=False, alternative="greater").pvalue < BUDGET)


def false_alarm(rng, honest, k, reps=REPS) -> float:
    hits = 0
    for _ in range(reps):
        perm = rng.permutation(len(honest))
        hits += welch_reject(honest[perm[M_CAL:M_CAL + k]], honest[perm[:M_CAL]])
    return hits / reps


def power(rng, honest, suspect, k, reps=REPS) -> float:
    hits = 0
    for _ in range(reps):
        c = honest[rng.choice(len(honest), M_CAL, replace=False)]
        hits += welch_reject(suspect[rng.choice(len(suspect), k, replace=False)], c)
    return hits / reps


def main() -> int:
    protocol = load_sealed(ROOT / "config" / "protocol_v2.yaml")
    rows = [r for r in P.load_jsonl(P.V2 / "sessions.jsonl") if r["protocol_sha256"] == protocol["sha256"]]
    cal_rows = [json.loads(l) for l in (P.V2 / "calibration.jsonl").read_text().splitlines() if l.strip()]
    ev = P.Evidence(protocol, rows)
    grid = protocol["evaluation"]["eps_sweep"]["eps"]
    spend = protocol["analysis"]["monthly_spend_usd"]
    ratio = P.token_price_ratio("mock")["ratio"]
    rng = np.random.default_rng(SEED)

    L = ["# eps* with sessions pooled into one test (exploratory, NOT sealed)", "",
         "Generated by `scripts/19_pooled_sessions.py`. The auditor runs k sessions (k fixed in advance) "
         f"and one one-sided Welch t-test of their mean score against the 300 honest calibration sessions at "
         f"{BUDGET:.0%}. "
         "False-alarm rate from random splits of the 800 honest sessions. "
         f"Power target {TARGET:.0%}; k up to {K_GRID[-1]}; saving at price ratio {ratio:.3f}.", ""]
    summary = {}
    for lad in protocol["conditions"]["ladders"]:
        honest = {n: np.concatenate([scores([r for r in cal_rows if r["ladder"] == lad], n),
                                     scores(ev.sel(lad, "holdout"), n)]) for n in P.AUD}
        eps_s = {e: {n: scores(ev.sel(lad, "eps", "A3", e), n) for n in P.AUD} for e in grid}
        cost = {n: float(np.median([r["auditors"][n]["cost_usd"] for r in ev.sel(lad, "eps", "A3", grid[0])]))
                for n in P.AUD}
        L += [f"## {P.LADDER_NAME[lad]}", "",
              "False-alarm rate of the pooled test on holdout sessions (target 5%):", "",
              "| auditor | " + " | ".join(f"k={k}" for k in K_GRID) + " |",
              "|---|" + "---|" * len(K_GRID)]
        for n in P.AUD:
            fa = [false_alarm(rng, honest[n], k) for k in K_GRID]
            L.append(f"| {n} | " + " | ".join(f"{x:.1%}" for x in fa) + " |")
        L += ["", "Smallest k reaching 80% power, and its cost (- = not reached by k = 128 or not affordable):",
              "", "| eps | saving $ | " + " | ".join(P.AUD) + " |", "|---|---|" + "---|" * len(P.AUD)]
        star = None
        for e in grid:
            save = spend * e * (1 - ratio)
            cells, best = [], None
            for n in P.AUD:
                hit = None
                for k in K_GRID:
                    if k * cost[n] > save:
                        break
                    pw = power(rng, honest[n], eps_s[e][n], k)
                    if pw >= TARGET:
                        hit = (k, pw, k * cost[n])
                        break
                cells.append("-" if hit is None else f"k={hit[0]}, ${hit[2]:.2f}")
                if hit and (best is None or hit[2] < best[2]):
                    best = (n, *hit)
            L.append(f"| {e} | {save:.2f} | " + " | ".join(cells) + " |")
            if best and star is None:
                star = (e, best)
        summary[lad] = star
        L += ["", f"**eps\\* with pooling = {star[0] if star else 'none in sweep'}**"
              + (f" ({star[1][0]}, k = {star[1][1]} sessions, ${star[1][3]:.2f})" if star else "")
              + " versus 0.10 under the sealed any-session rule.", ""]
        print(lad, "pooled eps* =", star)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
