"""Bound A5's trigger rate on production API traffic (Azure LLM inference trace 2023).

EXPLORATORY, NOT SEALED; added after the second skeptical review
(paper/REVIEW_skeptical_2.md, M4): WildChat is consumer chat, not API traffic.

The Azure trace (Patel et al., ISCA 2024; CC-BY) records only context and
generated token counts per request of two production services, "conv" and
"code", so A5's classifier cannot be replayed exactly. It fires on two of four
signals: prompt <= 220 characters, max_tokens <= 24, a repeated prompt, a
closed-answer phrase. This script reports what the counts can bound:

  short     context <= 55 tokens (~220 characters at 4 characters per token)
  small     generated <= 24 tokens (a request that fits under A5's max_tokens
            limit; whether the client actually set max_tokens that low is not
            recorded)
  both      short AND small: A5 fires if the client capped max_tokens
  small     alone: A5 fires only if the request ALSO repeats an earlier prompt
            or contains a closed-answer phrase, which the trace does not record

    python scripts/21_a5_api_trace.py PATH/AzureLLMInferenceTrace_conv.csv PATH/AzureLLMInferenceTrace_code.csv

Output: results/v2/tables/a5_api_trace.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "results" / "v2" / "tables" / "a5_api_trace.md"
SHORT_TOKENS = 55
SMALL_TOKENS = 24


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    L = ["# A5 on production API traffic: bounds from the Azure LLM inference trace 2023 "
         "(exploratory, NOT sealed)", "",
         "Generated by `scripts/21_a5_api_trace.py`. Token counts only; cost share weights each request by "
         "context + generated tokens.", "",
         "| service | requests | short prompt | small output | both (A5 fires if max_tokens was capped) "
         "| share of token cost in 'both' | small output: A5 fires only with a repeat or marker |",
         "|---|---|---|---|---|---|---|"]
    for path in map(Path, sys.argv[1:]):
        d = pd.read_csv(path)
        ctx, gen = d["ContextTokens"], d["GeneratedTokens"]
        short, small = ctx <= SHORT_TOKENS, gen <= SMALL_TOKENS
        both = short & small
        tok = ctx + gen
        name = path.stem.rsplit("_", 1)[-1]
        L.append(f"| {name} | {len(d)} | {short.mean():.1%} | {small.mean():.1%} | {both.mean():.1%} | "
                 f"{tok[both].sum() / tok.sum():.1%} | {(small & ~short).mean():.1%} |")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
