"""The pooled-session test on EVERY arm, and the lowest dilution it catches while
staying specific (honest load balancing) and robust (benchmark-aware cheating).

EXPLORATORY, NOT SEALED; added after the third skeptical review
(paper/REVIEW_skeptical_3.md, M1). Uses the test of scripts/19_pooled_sessions.py
unchanged: one one-sided Welch t-test of k suspect sessions against 300 honest
calibration sessions at the 5% budget.

  1. Every arm at k = 16 (grid arms have 30 sessions each, so k <= 30 is the
     most that can be drawn without replacement).
  2. For each (eps, auditor) that reaches 80% power in 19_pooled_sessions.py,
     the same auditor at the same k on A11 (honest load balancing, 200
     sessions) and on A10 (benchmark-aware cheating, at min(k, 30)).
     "Specific and robust" = flags at most 5% of A11 audits AND catches A10 on
     at least 80% of audits.

    python scripts/22_pooled_all_arms.py

Output: results/v2/tables/pooled_all_arms.md
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from arena.protocol import load_sealed  # noqa: E402

_spec = importlib.util.spec_from_file_location("pooled19", ROOT / "scripts" / "19_pooled_sessions.py")
Q = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(Q)
P = Q.P

OUT = P.TAB / "pooled_all_arms.md"
K_ALL = 16
REPS = 1000
SPEC_MAX = 0.05
ROBUST_MIN = 0.80


def main() -> int:
    protocol = load_sealed(ROOT / "config" / "protocol_v2.yaml")
    rows = [r for r in P.load_jsonl(P.V2 / "sessions.jsonl") if r["protocol_sha256"] == protocol["sha256"]]
    cal_rows = [json.loads(l) for l in (P.V2 / "calibration.jsonl").read_text().splitlines() if l.strip()]
    ev = P.Evidence(protocol, rows)
    grid = protocol["evaluation"]["eps_sweep"]["eps"]
    spend = protocol["analysis"]["monthly_spend_usd"]
    ratio = P.token_price_ratio("mock")["ratio"]
    rng = np.random.default_rng(0)
    L = ["# Pooled-session test on every arm (exploratory, NOT sealed)", "",
         "Generated by `scripts/22_pooled_all_arms.py`, with the test of `19_pooled_sessions.py`. "
         f"Cells are the share of audits flagged; {REPS} bootstrap audits each.", ""]
    for lad in protocol["conditions"]["ladders"]:
        honest = {n: np.concatenate([Q.scores([r for r in cal_rows if r["ladder"] == lad], n),
                                     Q.scores(ev.sel(lad, "holdout"), n)]) for n in P.AUD}
        arm = {a: {n: Q.scores(ev.sel(lad, "grid", a), n) for n in P.AUD} for a in P.ARMS[1:]}
        a11 = {n: Q.scores(ev.sel(lad, "eps", "A11"), n) for n in P.AUD}
        cost = {n: float(np.median([r["auditors"][n]["cost_usd"] for r in ev.sel(lad, "eps", "A3", grid[0])]))
                for n in P.AUD}
        L += [f"## {P.LADDER_NAME[lad]}", "", f"### Every arm, k = {K_ALL} sessions", "",
              "| arm | " + " | ".join(P.AUD) + " |", "|---|" + "---|" * len(P.AUD)]
        for a in P.ARMS[1:]:
            pool = a11 if a == "A11" else arm[a]
            cells = ["-" if len(pool[n]) < K_ALL else f"{Q.power(rng, honest[n], pool[n], K_ALL, REPS):.0%}"
                     for n in P.AUD]
            L.append(f"| {a}{' (honest)' if not P.IS_SUB[a] else ''} | " + " | ".join(cells) + " |")

        L += ["", "### Lowest eps caught (80% power, k <= 128) by an auditor that also stays specific and robust",
              "", f"Specific: flags at most {SPEC_MAX:.0%} of A11 audits at the same k. Robust: catches A10 on at "
              f"least {ROBUST_MIN:.0%} of audits at min(k, 30).", "",
              "| eps | auditor | k | cost $ | A3 power | A11 flagged | A10 caught | specific and robust? |",
              "|---|---|---|---|---|---|---|---|"]
        first_ok = None
        for e in grid:
            save = spend * e * (1 - ratio)
            s3 = {n: Q.scores(ev.sel(lad, "eps", "A3", e), n) for n in P.AUD}
            for n in P.AUD:
                for k in Q.K_GRID:
                    if k * cost[n] > save:
                        break
                    pw = Q.power(rng, honest[n], s3[n], k, REPS)
                    if pw >= Q.TARGET:
                        f11 = Q.power(rng, honest[n], a11[n], k, REPS)
                        c10 = Q.power(rng, honest[n], arm["A10"][n], min(k, 30), REPS)
                        ok = f11 <= SPEC_MAX and c10 >= ROBUST_MIN
                        L.append(f"| {e} | {n} | {k} | {k * cost[n]:.2f} | {pw:.0%} | {f11:.0%} | {c10:.0%} | "
                                 f"{'yes' if ok else 'no'} |")
                        if ok and first_ok is None:
                            first_ok = (e, n, k, k * cost[n])
                        break
            if first_ok and first_ok[0] == e:
                break
        L += ["", f"**Lowest eps with a specific and robust pooled audit: "
              + (f"{first_ok[0]} ({first_ok[1]}, k = {first_ok[2]}, ${first_ok[3]:.2f} plus calibration)**"
                 if first_ok else "none in the sweep**"), ""]
        print(lad, "specific+robust pooled eps* =", first_ok)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
