"""Does honest latency drift within the live run?

EXPLORATORY, NOT SEALED; added after the third skeptical review
(paper/REVIEW_skeptical_3.md, M4). A pooled timing audit compares sessions run
at one time with honest calibration run at another. This checks, on the
committed live run, whether honest gpt-oss-120b latency on Groq changed between
the first and second half of a 25-minute window: the two honest servers (REF and
A0) are pooled, ordered by timestamp and split in half.

    python scripts/23_live_drift.py

Output: results/v2/tables/live_drift.md
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path

from scipy.stats import ks_2samp

ROOT = Path(__file__).resolve().parent.parent
OBS = ROOT / "results" / "live" / "observations.jsonl"
OUT = ROOT / "results" / "v2" / "tables" / "live_drift.md"


def main() -> int:
    rows = [json.loads(l) for l in OBS.read_text().splitlines() if l.strip()]
    honest = sorted((r for r in rows if r["label"] in ("REF", "A0") and r["ok"]), key=lambda r: r["ts"])
    half = len(honest) // 2
    a = [r["client_latency_s"] for r in honest[:half]]
    b = [r["client_latency_s"] for r in honest[half:]]
    ks = ks_2samp(a, b)
    fp_a = {r["system_fingerprint"] for r in honest[:half]}
    fp_b = {r["system_fingerprint"] for r in honest[half:]}
    L = ["# Honest latency drift within the live run (exploratory, NOT sealed)", "",
         "Generated by `scripts/23_live_drift.py`. REF and A0 (both honest gpt-oss-120b on Groq) pooled, "
         "ordered by time, split in half.", "",
         "| half | requests | from | to | median s | mean s |", "|---|---|---|---|---|---|",
         f"| first | {len(a)} | {honest[0]['ts'][11:19]} | {honest[half - 1]['ts'][11:19]} | "
         f"{statistics.median(a):.3f} | {statistics.mean(a):.3f} |",
         f"| second | {len(b)} | {honest[half]['ts'][11:19]} | {honest[-1]['ts'][11:19]} | "
         f"{statistics.median(b):.3f} | {statistics.mean(b):.3f} |", "",
         f"KS first vs second half: D = {ks.statistic:.3f}, p = {ks.pvalue:.2g}.", "",
         f"system_fingerprint values: {len(fp_a)} in the first half, {len(fp_b)} in the second, "
         f"{len(fp_a & fp_b)} shared."]
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
